# Generated by Django 4.1.5 on 2023-01-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('birth_date', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('e_mail', models.CharField(max_length=255)),
            ],
        ),
    ]
